---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package on CentOS7.6-Minimal, with upgrade latest update with official archive
    yum:
     name:
       - "{{ APACHE_PACKAGE }}"
       - "{{ PHP_PACKAGE }}"
     state: latest
     update_cache: yes
